import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';
import { characterKeys } from '../src/characters.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

const data = JSON.parse(readFileSync(resolve(ROOT, 'src/publicEntries.json'), 'utf-8'));
const entries = data.entries;

// Generate Routes.jsx with explicit paths for every entry
const routeLines = entries.map(e =>
  `  { path: '/scroll/${e.id}', element: <EntryPage /> }`
);

const characterLines = characterKeys.map((k) =>
  `  { path: '/characters/${k}', element: <CharacterPage char="${k}" /> }`
);

const content = `// Auto-generated by scripts/generate-routes.mjs — do not edit directly
import React from 'react'; // eslint-disable-line no-unused-vars -- required by SSG JSX transform
import CanonExplorer from './CanonExplorer';
import LandingPage from './LandingPage';
import CharacterPage from './CharacterPage';
import CharactersPage from './CharactersPage';
import TimelinePage from './TimelinePage';
import EntryPage from './pages/EntryPage';

export const routes = [
  { path: '/', element: <LandingPage /> },
  { path: '/canon', element: <CanonExplorer /> },
  { path: '/timeline', element: <TimelinePage /> },
  { path: '/characters', element: <CharactersPage /> },
${characterLines.join(',\n')},
${routeLines.join(',\n')},
];
`;

writeFileSync(resolve(ROOT, 'src/Routes.jsx'), content, 'utf-8');
console.log(`Generated Routes.jsx with ${entries.length + 4 + characterKeys.length} routes`);
