import React from 'react'; // eslint-disable-line no-unused-vars -- required by SSG JSX transform
import { Link } from 'react-router-dom';
import { Helmet } from 'react-helmet-async';
import data from './entries.json';

const CSS = `
@import url('https://fonts.googleapis.com/css2?family=Fraunces:opsz,wght@9..144,400;9..144,500;9..144,600&family=Newsreader:opsz,wght@6..72,400;6..72,500&family=Spline+Sans+Mono:wght@400;500&display=swap');
:root{background:#11100c;color:#eee6d5;font-family:'Newsreader',Georgia,serif;color-scheme:dark}*{box-sizing:border-box}body{margin:0;background:#11100c}a{color:inherit}
.one-home{--paper:#eee6d5;--dim:#b9af98;--line:#383225;--amber:#dda63b;--green:#829a7a;min-height:100vh;background:radial-gradient(circle at 82% 9%,rgba(221,166,59,.08),transparent 28%),linear-gradient(180deg,#15130e,#0f0e0b 72%);color:var(--paper)}
.one-nav{display:flex;align-items:center;justify-content:space-between;gap:24px;padding:22px clamp(22px,5vw,72px);border-bottom:1px solid var(--line);font-family:'Spline Sans Mono',monospace;font-size:11px;letter-spacing:.12em;text-transform:uppercase}.one-mark{text-decoration:none}.one-mark span{color:var(--amber)}.one-navlinks{display:flex;gap:22px}.one-navlinks a{color:var(--dim);text-decoration:none}.one-navlinks a:hover{color:var(--amber)}
.one-hero{min-height:72vh;display:grid;grid-template-columns:minmax(0,1.25fr) minmax(260px,.75fr);gap:clamp(40px,8vw,130px);align-items:center;padding:clamp(64px,10vw,140px) clamp(22px,7vw,110px)}.one-kicker,.one-label{font-family:'Spline Sans Mono',monospace;font-size:10px;letter-spacing:.22em;text-transform:uppercase;color:var(--amber)}.one-title{font-family:'Fraunces',serif;font-weight:500;font-size:clamp(58px,10vw,142px);line-height:.82;letter-spacing:-.035em;margin:22px 0 30px;max-width:8ch}.one-title em{display:block;font-weight:400;color:var(--amber)}.one-lead{max-width:650px;color:var(--dim);font-size:clamp(19px,2vw,25px);line-height:1.45;margin:0 0 34px}
.one-actions{display:flex;flex-wrap:wrap;gap:12px}.one-button{font-family:'Spline Sans Mono',monospace;font-size:11px;letter-spacing:.1em;text-transform:uppercase;text-decoration:none;padding:13px 17px;border:1px solid var(--amber);color:#17140d;background:var(--amber)}.one-button.secondary{color:var(--paper);background:transparent;border-color:var(--line)}.one-button.secondary:hover{border-color:var(--amber)}
.one-evidence{border:1px solid var(--line);padding:28px;background:rgba(31,28,20,.6);position:relative}.one-evidence:before{content:'';position:absolute;left:-1px;top:-1px;width:44px;height:3px;background:var(--amber)}.one-evidence blockquote{font-family:'Fraunces',serif;font-size:clamp(25px,3vw,38px);line-height:1.18;margin:25px 0 30px}.one-stamp{font-family:'Spline Sans Mono',monospace;font-size:10px;letter-spacing:.1em;color:var(--green);text-transform:uppercase}
.one-section{padding:clamp(64px,9vw,120px) clamp(22px,7vw,110px);border-top:1px solid var(--line)}.one-sectionhead{display:grid;grid-template-columns:180px 1fr;gap:30px;margin-bottom:45px}.one-section h2{font-family:'Fraunces',serif;font-weight:500;font-size:clamp(38px,5vw,68px);line-height:1;margin:0;max-width:13ch}.one-sectionintro{color:var(--dim);max-width:650px;font-size:19px;margin-top:18px}
.one-paths{display:grid;grid-template-columns:repeat(4,1fr);border-top:1px solid var(--line);border-left:1px solid var(--line)}.one-path{padding:27px;min-height:250px;border-right:1px solid var(--line);border-bottom:1px solid var(--line);text-decoration:none;display:flex;flex-direction:column;transition:background .2s}.one-path:hover{background:#201c14}.one-number{font-family:'Spline Sans Mono',monospace;color:var(--amber);font-size:10px}.one-path h3{font-family:'Fraunces',serif;font-weight:500;font-size:27px;line-height:1.1;margin:38px 0 12px}.one-path p{color:var(--dim);font-size:15px;margin:0}.one-enter{margin-top:auto;font-family:'Spline Sans Mono',monospace;font-size:10px;letter-spacing:.12em;text-transform:uppercase;color:var(--amber)}
.one-record{display:grid;grid-template-columns:1fr 1fr;gap:clamp(30px,8vw,120px);align-items:end}.one-record p{color:var(--dim);font-size:19px;max-width:630px}.one-stats{display:grid;grid-template-columns:1fr 1fr;border:1px solid var(--line)}.one-stat{padding:24px;border-right:1px solid var(--line)}.one-stat:last-child{border:0}.one-stat strong{display:block;font-family:'Fraunces',serif;font-size:48px;font-weight:500;color:var(--amber)}.one-stat span{font-family:'Spline Sans Mono',monospace;font-size:9px;letter-spacing:.14em;text-transform:uppercase;color:var(--dim)}
.one-foot{padding:30px clamp(22px,7vw,110px);display:flex;justify-content:space-between;gap:20px;border-top:1px solid var(--line);font-family:'Spline Sans Mono',monospace;font-size:9px;letter-spacing:.1em;text-transform:uppercase;color:#847d6c}.one-foot a{color:var(--dim);text-decoration:none}
@media(max-width:850px){.one-hero,.one-record{grid-template-columns:1fr}.one-evidence{max-width:560px}.one-sectionhead{grid-template-columns:1fr}.one-paths{grid-template-columns:1fr 1fr}}@media(max-width:520px){.one-navlinks a:first-child{display:none}.one-paths{grid-template-columns:1fr}.one-title{font-size:64px}.one-foot{flex-direction:column}}@media(prefers-reduced-motion:no-preference){.one-title,.one-lead,.one-actions{animation:one-rise .65s ease both}.one-lead{animation-delay:.08s}.one-actions{animation-delay:.15s}@keyframes one-rise{from{opacity:0;transform:translateY(14px)}to{opacity:1;transform:none}}}
`;
const paths=[['01','Meet One','An undiscovered artist, trained political thinker, and conscience who refuses the throne.','/scroll/bio_one'],['02','One & Sandi','Love under surveillance, inheritance, and the machinery of public power.','/scroll/scroll_of_sandi_ii_the_file_on_one'],['03','The Stolen Voice','The Baptist disappears. A synthetic copy begins speaking in his place.','/scroll/scroll_of_the_baptist_iii'],['04','Carmichael','A president learns to convert crisis, grievance, and spectacle into authority.','/scroll/scroll_of_carmichael_i']];

export default function LandingPage(){const publicHeads=data.entries.filter(e=>e.visibility==='public'&&e.isHead);const canonHeads=publicHeads.filter(e=>e.status==='canon');return <><Helmet><title>Scrolls of One — A Universe of Conscience and Contested Truth</title><meta name="description" content="Enter the Voice of One universe: a literary archive about conscience, power, synthetic voices, and the difficult work of knowing whom to believe."/><link rel="canonical" href="https://scrollsofone.com/"/><style>{CSS}</style></Helmet><main className="one-home">
<nav className="one-nav" aria-label="Primary navigation"><Link className="one-mark" to="/"><span>●</span> Scrolls of One</Link><div className="one-navlinks"><a href="#enter">Enter the universe</a><Link to="/canon">The Canon</Link></div></nav>
<section className="one-hero"><div><div className="one-kicker">The Voice of One · A literary universe</div><h1 className="one-title">Who can <em>you believe?</em></h1><p className="one-lead">In a world where every voice can be manufactured, conscience is no longer an abstraction. It is a method of survival.</p><div className="one-actions"><a className="one-button" href="#enter">Enter the universe</a><Link className="one-button secondary" to="/canon">Open the canon record</Link></div></div><aside className="one-evidence" aria-label="The central question"><div className="one-label">Recovered record · Foundation</div><blockquote>“One works through method—constraining implementation rather than commanding the agenda.”</blockquote><div className="one-stamp">● Canon verified</div></aside></section>
<section className="one-section" id="enter"><div className="one-sectionhead"><div className="one-label">Four entrances</div><div><h2>Choose where the record opens.</h2><p className="one-sectionintro">This universe can be entered through conscience, love, imitation, or power. Each path leads into the same contested history.</p></div></div><div className="one-paths">{paths.map(([n,t,c,to])=><Link className="one-path" to={to} key={t}><span className="one-number">{n}</span><h3>{t}</h3><p>{c}</p><span className="one-enter">Read the record →</span></Link>)}</div></section>
<section className="one-section one-record"><div><div className="one-label">The canon archive</div><h2>The story has a record.</h2><p>Every public scroll, scene, letter, profile, and protocol is identified by status and place in the universe. Draft history remains preserved without being mistaken for current canon.</p><div className="one-actions" style={{marginTop:'28px'}}><Link className="one-button secondary" to="/canon">Browse the complete record</Link></div></div><div className="one-stats"><div className="one-stat"><strong>{publicHeads.length}</strong><span>Public works</span></div><div className="one-stat"><strong>{canonHeads.length}</strong><span>Canonical heads</span></div></div></section>
<footer className="one-foot"><span>Scrolls of One · The Voice of One universe</span><a href="https://emergenceinstitute.live">A project of the Emergence Institute ↗</a></footer></main></>}
